#
# Makefile
#

include $(GAIA_DIR)/src/main/make/Makefile.mk

# `rocket` --------------------------------------------------------------------------------------------------

NAME        := test-rocket-C++
CC_FILES    := test/rocket/test-C++.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Exception
CC_FILES    := test/rocket/test-Exception.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Guard
CC_FILES    := test/rocket/test-Guard.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Process
CC_FILES    := test/rocket/test-Process.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-StringConvert
CC_FILES    := test/rocket/test-StringConvert.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Type
CC_FILES    := test/rocket/test-Type.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-assert
CC_FILES    := test/rocket/test-assert.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-base
CC_FILES    := test/rocket/test-base.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-boost-spirit-x3
CC_FILES    := test/rocket/test-boost-spirit-x3.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-cl
CC_FILES    := test/rocket/test-cl.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-codec
CC_FILES    := test/rocket/test-codec.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-codec-global
CC_FILES    := test/rocket/test-codec-global.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-codec-rocket
CC_FILES    := test/rocket/test-codec-rocket.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-codec-std
CC_FILES    := test/rocket/test-codec-std.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-container
CC_FILES    := test/rocket/test-container.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-enum
CC_FILES    := test/rocket/test-enum.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-escape
CC_FILES    := test/rocket/test-escape.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-format
CC_FILES    := test/rocket/test-format.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-format-global
CC_FILES    := test/rocket/test-format-global.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-format-std
CC_FILES    := test/rocket/test-format-std.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-io
CC_FILES    := test/rocket/test-io.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-log
CC_FILES    := test/rocket/test-log.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-macro
CC_FILES    := test/rocket/test-macro.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-math
CC_FILES    := test/rocket/test-math.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-math-func
CC_FILES    := test/rocket/test-math-func.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-nio
CC_FILES    := test/rocket/test-nio.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-reflect
CC_FILES    := test/rocket/test-reflect.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-std
CC_FILES    := test/rocket/test-std.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-strings
CC_FILES    := test/rocket/test-strings.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-system
CC_FILES    := test/rocket/test-system.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-terminal
CC_FILES    := test/rocket/test-terminal.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-text
CC_FILES    := test/rocket/test-text.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-unicode
CC_FILES    := test/rocket/test-unicode.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

# `rocket-gtest` --------------------------------------------------------------------------------------------

NAME        := test-rocket-gtest-matcher
CC_FILES    := test/rocket-gtest/test-matcher.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

# All -------------------------------------------------------------------------------------------------------

build: $(BUILD_DEPS)

doc:
	@mkdir -p $(BUILD_DIR)/test/doc
	@$(DOXYGEN) $(DOXYGEN_FLAGS) src/test/Doxyfile

test: $(TEST_DEPS)

TESTS_DEPS := $(addprefix test-,$(TESTS))

tests: $(TESTS_DEPS)

# EOF
