#
# Makefile
#

include $(GAIA_DIR)/src/main/make/Makefile.mk

# `rocket` --------------------------------------------------------------------------------------------------

NAME        := test-rocket-C++
CC_FILES    := test/rocket/test-C++.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Exception
CC_FILES    := test/rocket/test-Exception.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Guard
CC_FILES    := test/rocket/test-Guard.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Process
CC_FILES    := test/rocket/test-Process.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-StringConvert
CC_FILES    := test/rocket/test-StringConvert.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-Type
CC_FILES    := test/rocket/test-Type.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-assert
CC_FILES    := test/rocket/test-assert.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-enum
CC_FILES    := test/rocket/test-enum.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-macro
CC_FILES    := test/rocket/test-macro.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-number
CC_FILES    := test/rocket/test-number.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-rocket
CC_FILES    := test/rocket/test-rocket.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-std
CC_FILES    := test/rocket/test-std.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-cl-cl
CC_FILES    := test/rocket/cl/test-cl.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-container-container
CC_FILES    := test/rocket/container/test-container.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-escape-escape
CC_FILES    := test/rocket/escape/test-escape.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-experimental-boost-spirit-x3
CC_FILES    := test/rocket/experimental/test-boost-spirit-x3.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-format-format
CC_FILES    := test/rocket/format/test-format.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-format-format-global
CC_FILES    := test/rocket/format/test-format-global.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-format-format-std
CC_FILES    := test/rocket/format/test-format-std.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-io-io
CC_FILES    := test/rocket/io/test-io.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-log-log
CC_FILES    := test/rocket/log/test-log.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-math-math
CC_FILES    := test/rocket/math/test-math.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-math-math-func
CC_FILES    := test/rocket/math/test-math-func.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-nio-nio
CC_FILES    := test/rocket/nio/test-nio.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-reflect-reflect
CC_FILES    := test/rocket/reflect/test-reflect.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-str-str
CC_FILES    := test/rocket/str/test-str.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-system-system
CC_FILES    := test/rocket/system/test-system.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-terminal-terminal
CC_FILES    := test/rocket/terminal/test-terminal.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-text-text
CC_FILES    := test/rocket/text/test-text.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

NAME        := test-rocket-unicode-unicode
CC_FILES    := test/rocket/unicode/test-unicode.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

# `rocket-gtest` --------------------------------------------------------------------------------------------

NAME        := test-rocket-gtest-matcher-matcher
CC_FILES    := test/rocket-gtest/matcher/test-matcher.cc
SHARED_LIBS := $(call shared-lib-name,rocket,$(ROCKET_VERSION))
include $(GAIA_DIR)/src/main/make/test-executable.mk

# All -------------------------------------------------------------------------------------------------------

build: $(BUILD_DEPS)

doc:
	@mkdir -p $(BUILD_DIR)/test/doc
	@$(DOXYGEN) $(DOXYGEN_FLAGS) src/test/Doxyfile

test: $(TEST_DEPS)

TESTS_DEPS := $(addprefix test-,$(TESTS))

tests: $(TESTS_DEPS)

# EOF
